# -*- coding: utf-8 -*-
"""FinalMLModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ipuRqq8YHyA8OQT1rOcuzhMVO6kyIbub

# **Problem Definition**

Predict product demand (Units) using historical pharma sales data
to assist Pharmevo in demand planning.

# **Importing Libraries**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import GridSearchCV

"""# **Importing File In Google Collab**"""

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("SalesData#2.csv", encoding="latin1")
df.head()

"""# **Data Preprocessing**"""

df["Invoice Date"] = pd.to_datetime(df["Invoice Date"], dayfirst=True)
df["Month"] = df["Invoice Date"].dt.month

df = df[df["Units"] > 0]  # remove returns

"""# **Feature Selection & Encoding**"""

features = ["Product", "Distributor Name", "Client Type", "Team", "Month", "Price", "Discount"]
target = "Units"

df = df[features + [target]]

for col in ["Product", "Distributor Name", "Client Type", "Team"]:
    df[col] = LabelEncoder().fit_transform(df[col])

"""# **Train-Test Split**"""

X = df[features]
y = df[target]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""# **Model Selection & Training**"""

model = GradientBoostingRegressor(
    n_estimators=200,
    learning_rate=0.05,
    random_state=42
)

model.fit(X_train, y_train)

"""# **Model Evaluation**"""

preds = model.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, preds))
print("RMSE:", rmse)

"""# **Hyperparameter Tuning**"""

params = {
    "n_estimators": [100, 200],
    "learning_rate": [0.05, 0.1]
}

grid = GridSearchCV(GradientBoostingRegressor(), params, cv=3)
grid.fit(X_train, y_train)

"""# **Save Model**"""

from google.colab import files
files.download("model.pkl")

import pickle
pickle.dump(model, open("model.pkl", "wb"))

from google.colab import files
files.download("model.pkl")

!pip install streamlit
!streamlit run app.py

