# -*- coding: utf-8 -*-
"""FinalEDAProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15nLbXkNsVM3iadDT4pwFwAMm8ipC8rYg

# **Problem Statement**

Pharmevo wants to analyze historical sales transactions to understand sales drivers and predict future product demand (Units) to support inventory planning and sales strategy.

Objective:
Analyze Pharmevo pharmaceutical sales data to understand sales trends,
customer behavior, and key drivers affecting product demand.

# **Importing Libraries**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""# **Importing File In Google Collab**"""

from google.colab import files
uploaded = files.upload()

"""# **Data Collection**"""

df = pd.read_csv("SalesData#2.csv", encoding="latin1")
df.head()

"""# **Data Understanding & Cleaning**"""

df.info()

df.isnull().sum()

# Convert date
df["Invoice Date"] = pd.to_datetime(df["Invoice Date"], dayfirst=True)

# Remove unnamed column
df = df.drop(columns=["Unnamed: 0"], errors="ignore")
df.head(3)

"""# **Feature Engineering for EDA**"""

df["Month"] = df["Invoice Date"].dt.month
df["Year"] = df["Invoice Date"].dt.year

"""# **Top 10 Products by Units**"""

df.groupby("Product")["Units"].sum().sort_values(ascending=False).head(10).plot(kind="bar")

"""# **Top Distributors by Sales Value**"""

df.groupby("Distributor Name")["Value Np"].sum().sort_values(ascending=False).head(10).plot(kind="bar")

"""# **Client Type Contribution**"""

# Filter out negative units for pie chart, as pie charts cannot represent negative values
df[df['Units'] > 0].groupby('Client Type')['Units'].sum().plot(kind='pie', autopct='%1.1f%%')

"""# **Discount vs Units (Impact)**"""

df.plot.scatter(x="Discount", y="Units", title="Discount Impact on Sales")

"""# **Team Performance Comparison**"""

df.groupby("Team")["Units"].sum().plot(kind="bar")

"""# **Price Distribution**"""

df["Price"].hist(bins=30)